ARG IMAGE_REF
FROM docker.io/${IMAGE_REF}

# TRY USING INETD TO RUN AN HTTP APP, SINCE INOTIFYWAIT DOES NOT WORK FROM HOST TO CONTAINER

RUN apk update && \
    apk add inotify-tools

COPY hotload.sh changes.sh /

ENTRYPOINT ["/bin/sh", "/hotload.sh"]
