ARG COMPILE_IMAGE_REF
FROM docker.io/${COMPILE_IMAGE_REF} AS build

RUN cd /src; \
	go vet ./...; \
	go fmt ./...; \
	go build ./...; \
	mv app /program

ARG RUN_IMAGE_REF
FROM docker.io/${RUN_IMAGE_REF}

RUN mkdir /app

COPY --from=build /program /app

ENTRYPOINT ["/app/program"]
