ARG BASE_IMAGE_REF
FROM docker.io/${BASE_IMAGE_REF} AS build

COPY app /app

RUN cd /app; \
	go vet ./...; \
	go fmt ./...; \
	go build ./...; \
	cp /app/app /program; \
	ls /program

ENTRYPOINT ["/program"]
