ARG COMPILE_IMAGE_REF
FROM docker.io/${COMPILE_IMAGE_REF} AS build

COPY app /app

RUN cd /app; \
	go vet ./...; \
	go fmt ./...; \
	go build ./...; \
	cp /app/app /program

ARG RUN_IMAGE_REF
FROM docker.io/${RUN_IMAGE_REF}

RUN mkdir /app

COPY --from=build /program /app

ENTRYPOINT ["/app/program"]
