// SPDX-License-Identifier: Apache-2.0
:doctype: article

= QEMU VMs

The files in this directory are related to creating QEMU VMs.

== mac-m1-archlinux-arm.sh

Last Tested: Jan 4, 2023 on MacOS Ventura

A self contained script to create an Arch Linux ARM 64 QEMU VM for an M1 Mac.
The following steps are required (the script has lots of comments for more details):

* mkdir archlinux
* cd archlinux
* curl -LO https://raw.githubusercontent.com/bantling/tools/master/qemu-vms/mac-m1-qemu-arch-arm.sh
* chmod +x mac-m1-qemu-arch-arm.sh
* ./mac-m1-qemu-arch-arm.sh
* Wait for VM to complete booting and autologin, and enter next command sequence
* mount /dev/vda1 /mnt && /mnt/setup.sh
* When the VM quits, enter next command on Mac host for first boot of new Arch Linux VM
* ./run.sh
* When VM starts, quickly hit ESC to enter EFI BIOS
* Choose Boot Manager
* Choose EFI Shell
* Wait for 5 second delay, then startup.nsh executes
* Login as root/root, and enter next few commands
* First command alters EFI BIOS Boot Order so VM comes first
* Second command resizes EXT4 filesystem to fill the unused space of the virtual HD
* ./set-boot.sh
* ./resize.sh
* halt -p
* On Mac host, execute ./run.sh again
* The VM now boots into the Arch Linux VM without using the EFI Shell
* Once your satisfied it works, you can remove the temp directory to save some disk space
* The set-boot.sh script can be executed anytime in the future if somehow the EFI boot order is wrong
* The resize.sh script can be executed anytime in the future after expanding the size of the virtual hard disk on the host
* The host virtual hard disk is initially 8GB (sparse and compressed to about 550MB), and can be expanded as follows:
* qemu-img resize archlinux.qcow2 +8G

The script downloads an application bundle ArchLinux.app that can be run from the Finder or Dock.
The correct icon for the bundle is a blue Arch Linux "A".
The icon is probably not showing correctly after the download. To fix that, duplicate the bundle, delete the original bundle, and rename the duplicate to ArchLinux.app.
If you drag the icon into the Dock, it may display some other icon, like the "sewing mat" icon (has lines and circles in it). To fix that, remove it from the Dock and copy it to the Dock again. You may need to restart and try removing/adding to the Dock again.

If you rerun the mac-m1-qemu-arch-arm.sh script, it will generate a new archlinux.qcow2 image.

The run.sh script forwards two ports:

* host port 2222 to guest port 22 for SSH (preconfigured in the VM)
* host port 4445 to guest port 445 in case you want to run Samba (have to install yourself)

The script uses the showcursor=on display option in case you want to run X windows.

The ArchLinux.app bundle runs the run.sh script, so any changes you make to run.sh affect the VM whether yor run it from the command line, Finder, or Dock.

Enjoy!

== qemu-arch-x86*.sh

[cols="1,1"]
|===
|File
|Purpose


|qemu-arch-x86_64.sh
|Create a bootable Arch Linux x86_64 8GB image

|qemu-arch-x86_64-expect.sh
|Expect script used to automate the Arch Linux installer

|qemu-arch-x86_64-resize.sh
|Resize script located at /install/resize.sh inside generated image
|===

Scripts that generate a bootable Arch Linux x86_64 image with the following features:

* Uses partition UUID for mounting root
* One partition for boot, bootloader, and root
* Networking setup
* Can use virtio or sata interface for disk image and network interface
* Uses syslinux bootloader
* Installs pacman packages from 1 week prior to date script is run, to avoid issues that occasionally occur with todays packages
* Installs packages needed for resize script

The qemu-arch-x86.sh script requires zsh shell, which Mac OS X uses by default. The script depends on some OS X commands
for (un)mounting a filesystem in an image.

Just run the qemu-arch-x86.sh, and it will:

* Download latest iso installer
* Download latest b2sum
* Verify generated b2sum matches downloaded sum
* Create an 8GB raw disk image named archlinux-x86_64.img

Enjoy!
